name: Continous Integration (CI)

on:
  pull_request:

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        architecture: ['x64']
        python-version: ['3.9', '3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: make install

      - name: Lint
        run: make lint

  unit:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        architecture: ['x64']
        python-version: ['3.9', '3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: make install

      - name: Run unit tests
        run: make unit
        env:
          MIN_VALID_EVENTS: "10"
          GOOGLE_APPLICATION_CREDENTIALS: tests/unit/fixtures/fake_credentials.json

      - name: Run coverage report
        run: make coverage

  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '${{ vars.PYTHON_VERSION }}'

      - name: Install dependencies
        run: make install

      - name: Audit for CVEs
        run: make audit

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - uses: actions/checkout@v4
      - uses: docker/setup-docker-action@e61617a16c407a86262fb923c35a616ddbe070b3 # v4.6.0

      - name: Build Docker image
        run: make docker_build
