name: Release to PyPI

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: read

jobs:
  release-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '${{ vars.PYTHON_VERSION }}'
          architecture: 'x64'

      - name: Run all tests
        run: make
        env:
          MIN_VALID_EVENTS: "10"
          GOOGLE_APPLICATION_CREDENTIALS: tests/unit/fixtures/fake_credentials.json

      - name: Release PyPI package
        run: make deploy
